### PR TITLE
Stop on errors

### LINKED ISSUE #121: Handle errors in data more gracefully
Reported in this `rabbitmq-users` discussion thread

https://groups.google.com/d/topic/rabbitmq-users/Q_eshGHI-bc/discussion

To reproduce, use this branch:

https://github.com/rabbitmq/rabbitmq-web-stomp-examples/tree/lrb-bad_escape

Start RabbitMQ:

```
make PLUGINS='rabbitmq_management rabbitmq_stomp rabbitmq_web_stomp rabbitmq_web_stomp_examples' run-broker
```

Visit the "Echo Server" example, and the crash will happen on the initial `SUBSCRIBE`

### PR DESCRIPTION
**Pull request by lukebakken**
Rather than crashing with `case_clause`, errors returned in the data
handlers should result in the orderly shutdown of the STOMP connection.

Fixes #121

@essen I'm curious, I noticed that returning `{stop, State}` is a deprecated call result:

https://github.com/ninenines/cowboy/blob/2.6.1/src/cowboy_websocket.erl#L43-L47

What will eventually be the correct way to return `stop`?

### CODE REVIEW

**Comment by lukebakken** [comment]
@essen thanks for the explanation.

**Comment by lukebakken** [comment]
@michaelklishin here is what is returned to the client in the error case now (from Wireshark):

```
WebSocket
    1... .... = Fin: True
    .000 .... = Reserved: 0x0
    .0.. .... = Per-Message Compressed: False
    .... 1000 = Opcode: Connection Close (8)
    1... .... = Mask: True
    .001 0101 = Payload length: 21
    Masking-Key: 3d69f6c0
    Masked payload
    Payload
        Close
            Status code: Invalid frame payload data (1007)
            Reason: {bad_escape,"\\\n"}
```

File: src/rabbit_web_stomp_handler.erl [hunk 1]
```diff
@@ -267,11 +272,14 @@ maybe_block(State = #state{state = blocking, heartbeat = Heartbeat},
...
-stop(State = #state{proc_state = ProcState}) ->
+stop(State) ->
+    stop(State, 1000, "STOMP died").
+
+stop(State = #state{proc_state = ProcState}, CloseCode, Error) ->
     maybe_emit_stats(State),
     ok = file_handle_cache:release(),
     rabbit_stomp_processor:flush_and_die(ProcState),
-    {reply, {close, 1000, "STOMP died"}, State}.
+    {reply, {close, CloseCode, Error}, State}.
```
Comment (essen) [inline src/rabbit_web_stomp_handler.erl:282]: While you're at it you can convert to `{[{close, CloseCode, Error}], State}`, the `reply` is also deprecated. But I'm fine with the patch otherwise either way.

Comment (lukebakken) [reply src/rabbit_web_stomp_handler.erl]: Done, thanks @essen

**Comment by lukebakken** [comment]
Backported to `v3.8.x`

**Comment by michaelklishin** [comment]
Thank you, @lukebakken.
